<a href="https://colab.research.google.com/github/RanjithReddavena/ML_23AG1A66I0/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np

In [45]:
list1=[8,7,6,5]
arr1=np.array(list1)
print(arr1)

[8 7 6 5]


In [46]:
list2=([[4,3,2,1],[6,7,8,9]])
arr2=np.array(list2)
print(arr2)

[[4 3 2 1]
 [6 7 8 9]]


In [47]:
list3=([9,0,1,2],[4,3,2,1],[6,7,8,9])
arr3=np.array(list3)
print(arr3)

[[9 0 1 2]
 [4 3 2 1]
 [6 7 8 9]]


In [48]:
arr1=np.array([2,4,8,9])
print(arr1.dtype)

int64


In [49]:
print(arr1.ndim)

1


In [50]:
print(arr1.shape)

(4,)


In [51]:
arr2=np.array([[2,3,4],[5,7,6]])
print(arr2.shape)

(2, 3)


In [52]:
print(arr2.itemsize)

8


In [53]:
print(arr1.itemsize)

8


In [54]:
print(arr2.data)

In [55]:
print(arr1[1])
print(arr1[2])
print(arr1[0])
print(arr1[-1])

4
8
2
9


In [56]:
arr1[1]=10
print(arr1[1])

10


In [57]:
list3=([9,0,1,2],[4,3,2,1],[6,7,8,9])
arr3=np.array(list3)
print(arr3[2,0])
print(arr3[2,-1])
print(arr3[0,0])

6
9
9


In [58]:
arr=[2,5,8,9,11,33,40]
print(arr)

[2, 5, 8, 9, 11, 33, 40]


In [59]:
print(np.mean(arr))

15.428571428571429


In [60]:
print(np.median(arr))

9.0


In [61]:
print(np.std(arr))

13.720236804049106


In [62]:
print(np.percentile(arr,10))

3.8000000000000003


In [63]:
print(np.min(arr))

2


In [64]:
print(np.max(arr))

40
